export const products = [
  {
    name: "Bananas Ecuador 1kl 2000 Pesos",
    categoria: "fyv",
    image: "https://imga",
    comercio: "El Local de Ceci",
    duracion: "21 - 28 Ene",
    precio: 2000,
  },
  {
    name: "Huevos Maple x $4000",
    categoria: "cyp",
    image: "https://imga",
    comercio: "El Local de Tito",
    duracion: "21 - 28 Ene",
    precio: 4000,
  },
  {
    name: "Leche Entera 1l $1500",
    categoria: "l",
    image: "https://imga",
    comercio: "El Local de Ceci",
    duracion: "21 - 28 Ene",
    precio: 1500,
  },
  {
    name: "Dulce de Leche 400g $2300",
    categoria: "ayd",
    image: "https://imga",
    comercio: "Alma Almacén",
    duracion: "21 - 28 Ene",
    precio: 2300,
  },
  {
    name: "Arroz Molino 1kl $2200",
    categoria: "syl",
    image: "https://imga",
    comercio: "Alma Almacén",
    duracion: "21 - 28 Ene",
    precio: 2200,
  },
  {
    name: "Cuadrada 1Kilo $7000",
    categoria: "cyp",
    image: "https://imga",
    comercio: "Carnicería Juancho",
    duracion: "21 - 28 Ene",
    precio: 7000,
  },
  {
    name: "Carne Asado 1Kl $6500",
    categoria: "cyp",
    image: "https://imga",
    comercio: "Carnicería Pepe",
    duracion: "21 - 28 Ene",
    precio: 6500,
  },
  {
    name: "Jamón Cocido 100g $600",
    categoria: "cyp",
    image: "https://imga",
    comercio: "Alma Almacén",
    duracion: "21 - 28 Ene",
    precio: 600,
  },
  {
    name: "Paty Express x4 $5500",
    categoria: "cyp",
    image: "https://imga",
    comercio: "Supermercado Sun",
    duracion: "21 - 28 Ene",
    precio: 5500,
  },
  {
    name: "Manos Cola 2.4l $1900",
    categoria: "b",
    image: "https://imga",
    comercio: "Comercio lo de Nano",
    duracion: "21 - 28 Ene",
    precio: 1900,
  },
  {
    name: "Manteca LaSere 400g $3200",
    categoria: "l",
    image: "https://imga",
    comercio: "El Local de Ceci",
    duracion: "21 - 28 Ene",
    precio: 3200,
  },
  {
    name: "Jugo Tang $300",
    categoria: "ayd",
    image: "https://imga",
    comercio: "Alma Almacén",
    duracion: "21 - 28 Ene",
    precio: 300,
  },
];

// carnes, lacteos, semillas y legumbres, pastas, frutas y verduras, grasas y aceites(manteca, aceites), azucares y dulces, bebidas
// una tienda x puede vender semillas, azucales y bebidas, los alimentos se clasifican en estas 8 categorías
// también podemos categorizar por precio, con 2000 pesos podes comprarte todo esto...
